#General Utilities
choco install chocolatey-core.extension
choco install chocolatey-compatibility.extension
choco install chocolatey-dotnetfx.extension
choco install 'dotnet4.5'
choco install 'dotnet4.6.1'
choco install flashplayeractivex
choco install flashplayerplugin
choco install javaruntime
choco install adobeair
choco install activeperl
choco install adobereader
choco install googlechrome
choco install firefox
choco install notepadplusplus.install
choco install python
choco install 7zip.install
choco install libreoffice-fresh
choco install greenshot
choco install openvpn
choco install obs-studio.install
choco install putty

#Forensics Tools
choco install access-data-registry-viewer
choco install nirlauncher
choco install photorec
choco install hindsight-gui
choco install exiftool
choco install hxd
choco install sysinternals 
choco install jq
choco install hindsight
choco install hindsight-gui
choco install wireshark
choco install tableau-imager
choco install hibernation-recon
choco install arsenalimagemounter
choco install dcode
choco install bulk-extractor
choco install aurora-ir
choco install volatility3
choco install mft2csv
choco install logfileparser
choco install ileapp-gui
choco install usnjrnl2csv
choco install aleapp
choco install sleuthkit
choco install radare2
choco install autopsy
choco install defraggler
choco install esedatabaseview
choco install free-pst-reader
choco install free-ost-reader
choco install logparser
choco install plaso
choco install timelineexplorer
choco install winprefetchview
choco install regripper
choco install shadowexplorer
choco install sqlitebrowser
choco install strings
choco install thumbs-viewer
choco install uniextract
choco install unxutils
choco install userassistview
choco install cyberchef
choco install yara